config/routes.rb
Rails.application.routes.draw do

   root  'static_pages#home'

   # Routes for static pages
   get '/home', to: 'static_pages#home'
   get '/search_home', to: 'static_pages#search_home'
   get '/help', to: 'static_pages#help'
   get '/about', to: 'static_pages#about'
   get '/convention', to: 'static_pages#convention'

   # Routes for users
   # TODO Need to rename http parameters when the time to create HR page comes
   resources 'users'
   get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
   patch 'users/:id/edit_password', to: 'users#update_password', as: 'update_password'
   get 'search_user/:id', to: 'users#search_user', as: 'search_user'

   # Routes for sessions
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout/:id', to: 'sessions#destroy', as: 'logout'

   # Routes for account managements
   get '/account_activation/:id', to: 'account_managements#account_activation', as: 'account_activation'
   get '/password_reset', to: 'account_managements#password_reset_new'
   post '/password_reset', to: 'account_managements#password_reset_create'

   # Routes for file uploaders
   resources 'uploaders', only: [] do
     member do
      get :user_thumbnail, as: :user_thumbnail
     end
   end

   # Routes for posts
   resources 'posts', only: [:new, :show, :edit, :create, :update, :destroy]

   # Routes for comments
   resources 'comments', only: [:edit, :create, :update, :destroy]
   get '/comments/:id', to: 'comments#new', as: 'new_comment'

   # Routes for reactions
   resources 'reactions', only: [:destroy]
   get '/reactions/:id', to: 'reactions#create', as: "new_reaction"

   resources 'conditions', only: [:show, :edit, :update]
   get '/conditions/:id/index', to: 'conditions#index', as: 'conditions'
   post '/conditions/new', to: 'conditions#create', as: "new_condition"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/condition.rb
class Condition < ApplicationRecord
   belongs_to :user
   belongs_to :post

   validates :user_id, presence: true
   validates :post_id, presence: true
   validates :category, presence: true
   validates :point, presence: true
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
   before_action :is_logged_in?
   before_action :interrupted?, only: [:show]
   before_action :url_log

   def index
      @user = User.find(params[:id])
      @conditions = @user.posts.where(post_type: "condition").where(published: true)
                    .order(:created_at).offset(2)
      respond_to do |format|
         format.html {}
         format.js {}
      end
   end

   def show
      @user = User.find(params[:id])
      @posts = @user.posts.where(post_type: "condition").where(published: true)
                    .order(:created_at).reverse_order.limit(2)
               @current_post = @posts.first
               @previous_post = @posts.last
      respond_to do |format|
         format.html {}
         format.js {}
      end
   end

   def edit
      @user = current_user
      @condition = Condition.find(params[:id])
      @question = Question.find_by(question_number: params[:question_number])
   end

   def create
      @user = current_user
      @post = current_user.posts.build(post_template("condition"))
      respond_to do |format|
         if time_to_answer?(current_user) == true
            @post.save
            10.times do |n|
               condition = current_user.conditions.build({post_id: @post.id, category: n + 1, point: 0})
               condition.save
            end
            @question = Question.find_by(question_number: 1)
            @condition = @post.conditions.find_by(category: @question.category)
            format.html { redirect_to edit_condition_url(@condition, question_number: 1) }
         else
            case time_to_answer?(current_user)
            when 1
               flash[:danger] = "次回の回答期間までこころチェック回答を制限しております。"
            when 0
               flash[:danger] = "回答期間外のこころチェック回答は受け付けておりません。"
            else
               flash[:danger] = "こころチェックの回答が制限されております"
            end
            format.html { redirect_to condition_url(current_user) }
         end
      end
   end

   def update
      @post = current_user.posts.where(post_type: "condition").last
      @condition = Condition.find(params[:id])
      @question_count = question_max?(params[:question_number])
      respond_to do |format|
         if @condition.update_attribute(:point, @condition.point + params[:point].to_i)
            if @question_count.nil?
               @post.update_attribute(:published, true)
               format.html { redirect_to condition_url(current_user) }
               format.js { render 'conditions/update' }
            else
               @question = Question.find_by(question_number: @question_count)
               @condition = @post.conditions.find_by(category: @question.category)
               format.html { redirect_to edit_condition_url(@condition, question_number: @question_count) }
               format.js { render 'conditions/update' }
            end
         end
      end
   end

   private
      def interrupted?
         unanswered_condition = current_user.posts.where(post_type: "condition").find_by(published: false)
          if unanswered_condition
             unanswered_condition.destroy
          end
      end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
   # Chart helpers
   def radar_params(current_post, previous_post)
      current_points = []
      current_conditions = current_post.conditions.order(:category)
      current_conditions.each do |condition|
         current_points << condition.point
      end

      previous_points = []
      previous_conditions = previous_post.conditions.order(:category)
      previous_conditions.each do |condition|
         previous_points << condition.point
      end
      return {
              labels: ["a.仕事の忙しさ", "b.プレッシャー",
                       "c.周囲の支え", "d.働く環境",
                       "e.職場への適応", "f.仕事への意欲",
                       "g.成果への挑戦", "h.成長実感",
                       "i.自己研鑽", "j.将来展望"],
              datasets: [
                {
                    label: "今回の結果",
                    background_color: 'rgba(241, 194, 192, 0.2)',
                    border_color: 'rgba(217, 83, 79, 0.6)',
                    border_width: 1,
                    point_background_color: 'rgba(217, 83, 79, 1)',
                    point_border_color: 'rgba(255, 255, 255, 1)',
                    point_hover_background_color: 'rgba(217, 83, 79, 1)',
                    point_hover_border_color: 'rgba(217, 83, 79, 1)',
                    data: current_points
                },
                {
                    label: "前回の結果",
                    background_color: 'rgba(192, 230, 242, 0.2)',
                    border_color: 'rgba(91, 192, 222, 0.6)',
                    border_width: 1,
                    point_background_color: 'rgba(91, 192, 222, 0.6)',
                    point_border_color: 'rgba(255, 255, 255, 1)',
                    point_hover_background_color: 'rgba(91, 192, 222, 1)',
                    point_hover_border_color: 'rgba(91, 192, 222, 1)',
                    data: previous_points
                }
              ]
            }
   end

   def radar_option
      return {
               tooltips: { enabled: false },
               scale: {
                  pointLabels: {
                        fontSize: 9,
                        fontFamily: "'メイリオ', 'Meiryo', 'ヒラギノ角ゴ Pro W3',
                        'Hiragino Kaku Gothic Pro', 'ＭＳ Ｐゴシック','MS PGothic'"
                      },
                  ticks: {
                     display: false,
                     min: 0,
                     max: 20,
                     stepSize: 5
               }
            }
         }
   end

   def line_params(posts)

      posts_date = Array.new(12, "")
      posts_burden = Array.new(12)
      posts_motivation = Array.new(12)
      n = 0

      posts.each do |post|
         posts_date[n] = [post.created_at.strftime("%Y年"), post.created_at.strftime("%m月%d日")]
         burdens = post.conditions.order(:category).limit(5)
         burden_point = 0
         burdens.each do |burden|
            burden_point += burden.point
         end
         posts_burden[n] = burden_point

         motivations = post.conditions.order(:category).reverse_order.limit(5)
         motivation_point = 0
         motivations.each do |motivation|
            motivation_point += motivation.point
         end
         posts_motivation[n] = motivation_point
         n += 1
      end

      result = {
         xLabels: posts_date,
         datasets: [
            {
               label: "負担感(注意・普通・良好)",
               fill: false,
               background_color: "rgba(255, 194, 179, 0.6)",
               border_color: "rgba(255, 71, 26, 0.6)",
               point_background_color: "rgba(255, 194, 179, 0.6)",
               data: posts_burden
            },
            {
               label: "モチベーション(低・中・高)",
               fill: false,
               background_color: "rgba(153, 214, 255, 0.6)",
               border_color: "rgba(51, 173, 255, 0.6)",
               point_background_color: "rgba(153, 214, 255, 0.6)",
               data: posts_motivation
            }
         ]
      }
   end

   def line_option
      return {
         width: 625,
         height: 260,
         tooltips: { enabled: false },
         responsive: false,
         maintainAspectRatio: false,
         onResize: false,
         span_gaps: false,
         scales: {
            xAxes: [{
               ticks: {
                  fontSize: 10,
                  beginAtZero: true
               },
               gridLines: { display: false }
            }],
            yAxes: [{
               ticks: {
                  display: false,
                  max: 100,
                  min: 20,
                  stepSize: 20
               },
            }]
         },
      }
   end

   # Recognize data from conditions

   def condition_summary(label, post)
      burdens = post.conditions.order(:category).limit(5)
      burden_point = 0
      burdens.each do |burden|
         burden_point += burden.point
      end
      burden_result = ""
      burden_class = ""
      if burden_point >= 20 && burden_point <= 36
         burden_result = "注意"
         burden_class = "danger"
      elsif burden_point >= 37 && burden_point <= 84
         burden_result = "ふつう"
         burden_class = "warning"
      elsif burden_point >= 85 && burden_point <= 100
         burden_result = "良好"
         burden_class = "info"
      else
         burden_result = "なし"
      end

      motivations = post.conditions.order(:category).reverse_order.limit(5)
      motivation_point = 0
      motivations.each do |motivation|
         motivation_point += motivation.point
      end
      motivation_result = ""
      motivation_class = ""
      if motivation_point >= 20 && motivation_point <= 44
         motivation_result = "低"
         motivation_class = "danger"
      elsif motivation_point >= 45 && motivation_point <= 76
         motivation_result = "中"
         motivation_class = "warning"
      elsif motivation_point >= 77 && motivation_point <= 100
         motivation_result = "高"
         motivation_class = "info"
      else
         motivation_result = "なし"
      end

      result = {}

      if label == "detail"
         result = {
                  burden: { class: burden_class, title: burden_result },
                  motivation: { class: motivation_class, title: motivation_result }
                  }
         return result
      end

      if burden_result == "注意" && motivation_result == "低"
         result = {
                  class: "exhausted",
                  title: "ヘトヘト",
                  image: "danger.png",
                  subtitle: "心身ともに限界の状態",
                  description: ""
                  }
      elsif burden_result == "注意" && (motivation_result == "中" || motivation_result == "低")
         result = {
                  class: "aggressive",
                  title: "ギリギリ",
                  image: "warning.png",
                  subtitle: "ギリギリな状態",
                  description: ""
                  }
      elsif (burden_result == "ふつう" || burden_result == "良好") && motivation_result == "低"
         result = {
                  class: "gloomy",
                  title: "モヤモヤ",
                  image: "warning.png",
                  subtitle: "モヤモヤな状態",
                  description: ""
                  }
      elsif (burden_result != "注意" && motivation_result != "低") &&
            (burden_result != "なし" && motivation_result != "なし")
         result = {
                  class: "vivacious",
                  title: "イキイキ",
                  image: "info.png",
                  subtitle: "仕事に打ち込めている状態",
                  description: ""
                  }
      else
         result = {
                  class: "nothing",
                  title: "未回答",
                  image: "blank.png",
                  subtitle: "こころチェックは行われておりません",
                  description: "質問に回答して自分のこころの状態を確認しましょう。"
                  }
      end

      case label
      when "class"
         return result[:class]
      when "title"
         return result[:title]
      when "image"
         return result[:image]
      when "subtitle"
         return result[:subtitle]
      when "description"
         return result[:description]
      else
      end
   end

   def condition_fa(label, position, post)
      if label == "burden"
         burdens = post.conditions.order(:category).limit(5)
         burden_point = 0
         burdens.each do |burden|
            burden_point += burden.point
         end
         if position == "danger" &&
            burden_point >= 20 && burden_point <= 36
            return 'check-square-o'
         elsif position == "warning" &&
            burden_point >= 37 && burden_point <= 84
            return 'check-square-o'
         elsif position == "info" &&
            burden_point  >= 85 && burden_point <= 100
            return 'check-square-o'
         else
            return 'square-o'
         end

      elsif label == "motivation"
         motivations = post.conditions.order(:category).reverse_order.limit(5)
         motivation_point = 0
         motivations.each do |motivation|
            motivation_point += motivation.point
         end
         if position == "danger" &&
            motivation_point >= 20 && motivation_point <= 44
            return 'check-square-o'
         elsif  position == "warning" &&
            motivation_point >= 45 && motivation_point <= 76
            return 'check-square-o'
         elsif position == "info" &&
            motivation_point >= 77 && motivation_point <= 100
            return 'check-square-o'
         else
            return 'square-o'
         end
      end
   end

   # Regulate to answer questionnaires if user does not meet conditions
   def time_to_answer?(user)
      term_current = Date.today
      term_start = Date.new(term_current.year, term_current.month, 15)
      term_end = Date.new(term_current.year, term_current.month, -1)

      if term_current >= term_start && term_current <= term_end
         user_latest_post = user.posts.where(post_type: "condition").order(:created_at).last

app/views/conditions/_form.html.erb
<div id="questions-edit" class="content-box">
   <p id="question-sentence">
      <%= @question.question_number %>：<%= @question.content %>
   </p>
   <ul id="question-answers">
      <li><%= button_to "あてはまる", condition_path(@condition, question_number: @question.question_number, point: 5), method: :put, class: 'btn', remote: true %></li>
      <li><%= button_to "どちらかというとあてはまる", condition_path(@condition, question_number: @question.question_number, point: 4), method: :put, class: 'btn', remote: true %></li>
      <li><%= button_to "どちらともいえない", condition_path(@condition, question_number: @question.question_number, point: 3), method: :put, class: 'btn', remote: true %></li>
      <li><%= button_to "どちらかというとあてはまらない", condition_path(@condition, question_number: @question.question_number, point: 2), method: :put, class: 'btn', remote: true %></li>
      <li><%= button_to "あてはまらない", condition_path(@condition, question_number: @question.question_number, point: 1), method: :put, class: 'btn', remote: true %></li>
   </ul>
</div>

app/views/conditions/_latest_condition.html.erb
<% if time_to_answer?(current_user) == true %>
   <div id="condition-notice" class="content-box">
      <div id="condition-frame">
         <p>
            <i class="fa fa-heartbeat animated infinite rubberBand"></i>
            <i class="fa fa-check"></i>
         </p>
         <ul class="notice-line">
            <li><h1>こころチェック</h1></li>
            <li><h1>回答期間です</h1></li>
         </ul>
         <ul class="notice-line">
            <li><h2>回答期間： </h2></li>
            <li><h2><%= Date.new(Date.today.year, Date.today.month, 15).strftime("%Y/%m/%d") %></h2></li>
            <li><h2> ～ </h2></li>
            <li><h2><%= Date.new(Date.today.year, Date.today.month, -1).strftime("%Y/%m/%d") %></h2></li>
         </ul>
         <%= link_to "回答する", new_condition_path, class: 'btn', method: :post %>
      </div>
   </div>
<% end %>

<div id="post-<%= @current_post.id %>" class="content-box condition-result">
   <div class="content-header">
      <p>最新のチェック結果</p>
   </div>
   <div id="condition-top">
      <p id="condition-date">更新日: <% if @posts.count > 2 %><%= @current_post.updated_at.strftime("%Y年%m日%d日") %><% end %></p>
      <div id="toggle-draft">
         <a href="#" id="toggled-publish" class="toggle-button toggle-active"><i class="fa fa-table"></i><span>最新</span></a>
         <%= link_to conditions_path(@user), id: 'toggled-draft', class: "toggle-button", remote: true do %><i class="fa fa-line-chart"></i><span>推移</span><% end %>
      </div>

   </div>
   <ul id="condition-header">
      <li id="condition-title">
         <span class="condition-<%= condition_summary('class', @current_post) %>"><%= condition_summary("title", @current_post) %> </span>
         <%= image_tag(condition_summary("image", @current_post)) %>
      </li>
   </ul>
   <div id="condition-description">
      <h1><%= condition_summary("subtitle", @current_post) %></h1>
      <p><%= condition_summary("description", @current_post) %></p>
   </div>

   <div id="condition-main-content">
      <div id="condition-radar-chart">
         <%= radar_chart radar_params(@current_post, @previous_post), radar_option %>
      </div>
      <div id="condition-summary">
         <p id="motivation" class="summary-header">モチベーション</p>
         <table id="motivation-table">
            <tr>
               <th><span>前回</span></th>
               <th></th>
               <th><span>今回</span></th>
            </tr>
            <tr>
               <td class="previous summary-info"><%= fa_icon(condition_fa('motivation', 'info', @previous_post)) %></td>
               <td></td>
               <td class="current summary-info"><%= fa_icon(condition_fa('motivation', 'info', @current_post)) %></td>
            </tr>
            <tr>
               <td class="previous summary-warning"><%= fa_icon(condition_fa('motivation', 'warning', @previous_post)) %></td>
               <td><i class="fa fa-arrow-right"></i></td>
               <td class="current summary-warning"><%= fa_icon(condition_fa('motivation', 'warning', @current_post)) %></td>
            </tr>
            <tr>
               <td class="previous summary-danger"><%= fa_icon(condition_fa('motivation', 'danger', @previous_post)) %></td>
               <td></td>
               <td class="current summary-danger"><%= fa_icon(condition_fa('motivation', 'danger', @current_post)) %></td>
            </tr>
         </table>

         <p id="burden" class="summary-header">負担感</p>
         <table id="burden-table">
            <tr>
               <th><span>前回</span></th>
               <th></th>
               <th><span>今回</span></th>
            </tr>
            <tr>
               <td class="previous summary-info"><%= fa_icon(condition_fa('burden', 'info', @previous_post)) %></td>
               <td></td>
               <td class="current summary-info"><%= fa_icon(condition_fa('burden', 'info', @current_post)) %></td>
            </tr>
            <tr>
               <td class="previous summary-warning"><%= fa_icon(condition_fa('burden', 'warning', @previous_post)) %></td>
               <td><i class="fa fa-arrow-right"></i></td>
               <td class="current summary-warning"><%= fa_icon(condition_fa('burden', 'warning', @current_post)) %></td>
            </tr>
            <tr>
               <td class="previous summary-danger"><%= fa_icon(condition_fa('burden', 'danger', @previous_post)) %></td>
               <td></td>
               <td class="current summary-danger"><%= fa_icon(condition_fa('burden', 'danger', @current_post)) %></td>
            </tr>
         </table>
      </div>
   </div>

   <div id="condition-words">
      <div id="words-list">
         <h1>内訳と説明</h1>
         <ul>
            <h2 class="list-section">負担感</h2>
            <li>a.仕事の忙しさ</li>
            <li>b.プレッシャー</li>
            <li>c.周囲の支え</li>
            <li>d.働く環境</li>
            <li>e.職場への適応</li>
         </ul>
         <ul>
            <h2 class="list-section">モチベーション</h2>
            <li>f.仕事への意欲</li>
            <li>g.成果への挑戦</li>
            <li>h.成長実感</li>
            <li>i.自己研鑽</li>
            <li>j.将来展望</li>
         </ul>
      </div>
      <div id="words-description">
         <h1 id="description-title">a.仕事の忙しさ</h1>
         <h2 id="description-summary">やるべきことが多く、時間的負荷を感じている度合い</h2>
         <ul>
            <li>
               <p>この結果が「<span class="words-info">良好</span>」「<span class="words-info">高</span>」の時は</p>
               <p><span class="words-info">---------------------------------</span></p>
               <p id="description-info">仕事をため込まずに進められている状態です。</p>
            </li>
            <li>
               <p>この結果が「<span class="words-danger">注意</span>」「<span class="words-danger">低</span>」の時は</p>
               <p><span class="words-danger">---------------------------------</span></p>
               <p id="description-danger">仕事を抱え込み過ぎて、身動きが取れない状態かもしれません。
                  例えば、ここ一週間の間にやった仕事と、割いた時間を書き出してみましょう。
                  冷静に見ると時間をかけ過ぎていた仕事や、あなたがやらなくてもよかった仕事があるかもしれません。
                  上司や周囲の先輩に、客観的なアドバイスをもらうのもよいでしょう。</p>
            </li>
         </ul>
      </div>
   </div>
   <% if condition_summary("class", @current_post) != "nothing" %>
         <div class="post-reaction">
         <% if @current_post.reactions.find_by(user_id: current_user.id).nil? %>
            <%= link_to reaction_path(@current_post), class: 'reaction-default', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= @current_post.reactions.count %></span><% end %>
         <% else %>
            <%= link_to reaction_path(@current_post), method: :delete, class: 'reaction-reacted', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= @current_post.reactions.count %></span><% end %>
         <% end %>
         <% if @current_post.reactions.count >= 1 %>
         <ul class="post-reaction-list">
            <% @current_post.reactions.each do |reaction| %>
            <li><%= reaction.user.name %></li>
            <% end %>
         </ul>
         <% end %>
         <%= link_to new_comment_path(@current_post), remote: true do %><i class="fa fa-comment-o"></i><span class="reaction-str">コメント</span><span><%= @current_post.comments.count %></span><% end %>
      </div>
   <% end %>
</div>
<div id="condition-download" class="content-box">
   <div id="download-frame">
      <ul class="notice-line">
         <li><h1>今回の結果をダウンロード</h1></li>
         <li><h1>(pdfファイル)</h1></li>
      </ul>
      <a href="#" class="btn">ダウンロード</a>
   </div>
</div>

app/views/conditions/_transition.html.erb
<div class="content-box condition-result">
   <div class="content-header">
      <p>これまでのチェック結果</p>
   </div>
   <div id="condition-top">
      <p id="condition-date">更新日: <% if @conditions.count > 0 %><%= @conditions.first.updated_at.strftime("%Y年%m日%d日") %><% end %></p>
      <div id="toggle-draft">
         <%= link_to condition_path(@user), id: 'toggled-draft', class: "toggle-button", remote: true do %><i class="fa fa-table"></i><span>最新</span><% end %>
         <a href="#" id="toggled-publish" class="toggle-button toggle-active"><i class="fa fa-line-chart"></i><span>推移</span></a>
      </div>

   </div>

   <div id="condition-graph">
      <p class="content-section">こころの状態：グラフ</p>
      <p>あなたのこころチェックの回答をもとに、負担感／モチベーション、仕事量の認知の推移を表示しています。</p>
      <%= render ('whole_conditions') %>
   </div>

   <div id="condition-table">
      <p class="content-section">こころの状態：一覧</p>
      <p>過去の報告書をまとめてダウンロードできます。</p>
      <table>
         <tr>
            <th class="table-date" rowspan="2">チェック日</th>
            <th class="table-result" rowspan="2">総合判定</th>
            <th class="table-detail" colspan="2">内訳</th>
         </tr>
         <tr>
            <th class="table-item">負担感</th>
            <th class="table-item">モチベーション</th>
         </tr>

         <% if @conditions.count > 0 %>
            <% @conditions.each do |post| %>
               <tr>
                  <td class="table-date">
                     <p><%= post.created_at.strftime("%Y年%m月%d日") %></p>
                     <div class="post-reaction">
                     <% if post.reactions.find_by(user_id: current_user.id).nil? %>
                        <%= link_to reaction_path(post), class: 'reaction-default', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= post.reactions.count %></span><% end %>
                     <% else %>
                        <%= link_to reaction_path(post), method: :delete, class: 'reaction-reacted', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= post.reactions.count %></span><% end %>
                     <% end %>
                     <% if post.reactions.count >= 1 %>
                     <ul class="post-reaction-list">
                        <% post.reactions.each do |reaction| %>
                        <li><%= reaction.user.name %></li>
                        <% end %>
                     </ul>
                     <% end %>
                     <%= link_to new_comment_path(post), remote: true do %><i class="fa fa-comment-o"></i><span class="reaction-str">コメント</span><span><%= post.comments.count %></span><% end %>
                  </div>
                  </td>
                  <td class="table-result">
                     <%= image_tag(condition_summary("image", post)) %>
                     <p class="table-<%= condition_summary('class', post) %>"><%= condition_summary("title", post) %></p>

                  </td>
                  <td class="table-item table-<%= condition_summary("detail", post)[:burden][:class] %>">
                     <%= condition_summary("detail", post)[:burden][:title] %>
                  </td>
                  <td class="table-item table-<%= condition_summary("detail", post)[:motivation][:class] %>">
                     <%= condition_summary("detail", post)[:motivation][:title] %>
                  </td>
               </tr>
            <% end %>
         <% end %>
      </table>
   </div>
</div>

<div id="condition-download" class="content-box">
   <div id="download-frame">
      <ul class="notice-line">
         <li><h1>今回の結果をダウンロード</h1></li>
         <li><h1>(pdfファイル)</h1></li>
      </ul>
      <a href="#" class="btn">ダウンロード</a>
   </div>
</div>

app/views/conditions/_whole_conditions.html.erb
<div id="condition-graph-chart">
   <ul id="graph-y-axes">
      <li><span>良好</span>/<span>高</span></li>
      <li><span>普通</span>/<span>中</span></li>
      <li><span>注意</span>/<span>低</span></li>
   </ul>
   <div id="graph-chart-frame">
      <%= line_chart line_params(@conditions), line_option %>
   </div>
</div>

app/views/conditions/edit.html.erb
<div id="container-single">
   <%= render 'conditions/form' %>
</div>

app/views/conditions/index.html.erb
<div id="container-left">
   <%= render('shared/user_status') %>
</div>

<div id="container-right">
   <%= render('conditions/transition') %>
</div>

app/views/conditions/index.js.erb
$('#container-right').html("<%= escape_javascript(render('conditions/transition')) %>");

app/views/conditions/show.js.erb
$('#container-right').html("<%= escape_javascript(render('conditions/latest_condition')) %>");

app/views/conditions/update.js.erb
<% if @question_count.nil?%>
   window.location.replace("<%= condition_path(current_user) %>");
<% else %>
   $('#container-single').html("<%= escape_javascript(render('conditions/form'))%>");
<% end %>