config/routes.rb
Rails.application.routes.draw do

   root  'static_pages#home'

   # Routes for static pages
   get '/home', to: 'static_pages#home'
   get '/search_home', to: 'static_pages#search_home'
   get '/help', to: 'static_pages#help'
   get '/about', to: 'static_pages#about'
   get '/convention', to: 'static_pages#convention'

   # Routes for users
   # TODO Need to rename http parameters when the time to create HR page comes
   resources 'users'
   get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
   patch 'users/:id/edit_password', to: 'users#update_password', as: 'update_password'
   get 'search_user/:id', to: 'users#search_user', as: 'search_user'

   # Routes for sessions
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout/:id', to: 'sessions#destroy', as: 'logout'

   # Routes for account managements
   get '/account_activation/:id', to: 'account_managements#account_activation', as: 'account_activation'
   get '/password_reset', to: 'account_managements#password_reset_new'
   post '/password_reset', to: 'account_managements#password_reset_create'

   # Routes for file uploaders
   resources 'uploaders', only: [] do
     member do
      get :user_thumbnail, as: :user_thumbnail
     end
   end

   # Routes for posts
   resources 'posts', only: [:new, :show, :edit, :create, :update, :destroy]

   # Routes for comments
   resources 'comments', only: [:edit, :create, :update, :destroy]
   get '/comments/:id', to: 'comments#new', as: 'new_comment'

   # Routes for reactions
   resources 'reactions', only: [:destroy]
   get '/reactions/:id', to: 'reactions#create', as: "new_reaction"

   resources 'conditions', only: [:show, :edit, :update]
   get '/conditions/:id/index', to: 'conditions#index', as: 'conditions'
   post '/conditions/new', to: 'conditions#create', as: "new_condition"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
   has_many :posts, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :reactions, dependent: :destroy
   has_many :conditions, dependent: :destroy

   before_create :generate_activation

   attr_accessor :remember_token, :activate_token, :password_reset_token

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w\d\-.]+\.[A-z]+\z/

   validates :name, presence: true,
                    length: { maximum: 20 }
   validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   validates :employee_number, presence: true,
                               length: { maximum: 8 }
   validates :division, presence: true,
                        length: { maximum: 50 }
   validates :gender, presence: true,
                      format: { with: /男|女/ }
   validates :started_at, presence: true
   validates :birthday, presence: true
   validates :employee, presence: true
   validates :password, presence: true,
                        length: { minimum: 8 },
                        allow_nil: true
   has_secure_password

   validate :file_valid?

   def remember
      self.remember_token = User.new_token
      self.update_attribute(:remember_digest, User.digest(self.remember_token))
   end

   def forget
      self.update_attribute(:remember_digest, nil)
   end

   def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
   end

   def User.new_token
      SecureRandom.urlsafe_base64
   end

   def authenticated?(attribute, token)
      field = self.send("#{attribute}_digest")
      return false if field.nil?
      BCrypt::Password.new(field).is_password?(token)
   end

   def send_activation_mail
      UserMailer.account_activation(self).deliver_now
   end

   def send_password_reset_mail
      UserMailer.password_reset(self).deliver_now
   end

   def password_expired?
      if self.password_reset? && self.password_reset_sent_at + 2.weeks <= Time.now
         return true
      else
         return false
      end
   end

   def uploaded_thumbnail=(thumbnail_field)
     self.thumbnail_ctype = thumbnail_field.content_type
     self.thumbnail = thumbnail_field.read
   end

   private
      def generate_activation
         self.activate_token = User.new_token
         self.activate_digest = User.digest(self.activate_token)
      end

      def file_valid?
        ps = ["image/jpeg", "image/jpg", "image/gif", "image/png"]
        errors.add(:thumbnail, 'is not an image file') if !self.thumbnail.nil? && !ps.include?(self.thumbnail_ctype)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_logged_in?
   before_action :url_log

  def index
     @users = User.all
  end

  def show
     @user = User.find(params[:id])
     @published = true
     if !params[:published].nil? || params[:published] == "0"
        @published = false
     end
     @posts = Post.page(params[:page]).where(user_id: @user.id).where(published: @published).order(:created_at).reverse_order
     respond_to do |format|
       format.html {}
       format.js {}
     end
  end

  def search_user
     @user = User.find(params[:id])
     @published = true
     @word = params[:post][:word]
     if !params[:post][:published].nil? || params[:post][:published] == "0"
       @published = false
     end
     @posts = Post.page(params[:page]).where(user_id: @user.id).where(published: @published).where("content LIKE ?", "%#{params[:post][:word]}%").order(:created_at).reverse_order
     respond_to do |format|
      format.js {}
     end
  end

  def new
     @user = User.new
  end

  def edit
     @user = User.find(params[:id])
  end

  def create
     @user = User.new(user_params)
     if @user.save
        @user.send_activation_mail
        @user.update_attribute(:password_reset_sent_at, Time.now)
        flash['success'] = "本登録のメールを送信しました。
        届いたメール内に記載されたURLをクリックして登録を完了してください"
        redirect_back_to(root_url)
     else
        flash['danger'] = "入力情報に不備があります"
        render 'users/new'
     end
  end

  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
         flash['success'] = "ユーザー情報を更新しました"
         redirect_back_to(root_url)
      else
         flash['danger'] = "入力情報に不備があります"
         render 'users/edit'
      end
  end

  def destroy
     @user = User.find(params[:id])
     if @user.destroy
         redirect_back_to(root_url)
     else
        redirect_back_to(root_url)
     end
  end

  def edit_password
     @user = User.find(params[:id])
  end

  def update_password
     @user = User.find(params[:id])
     if @user && @user.authenticate(params[:password][:current_password]) && params[:password][:new_password].length >= 8 &&
        params[:password][:new_password] == params[:password][:password_confirmation]
        if @user.update_attribute(:password_digest, User.digest(params[:password][:new_password]))
           @user.update_attribute(:password_reset, false)
           flash[:success] = "パスワードの変更を完了しました"
           redirect_back_to(root_url)
        else
           flash['danger'] = "新しいパスワードが有効ではありません"
           render 'users/edit_password'
        end
     else
        if !@user.authenticate(params[:password][:current_password])
           flash['danger'] = "現在のパスワードが正しく入力されていません"
        elsif params[:password][:new_password] != params[:password][:password_confirmation] || params[:password][:new_password].length < 8
           flash['danger'] = "新しいパスワードが正しく入力されていません"
        end
        render 'users/edit_password'
     end
  end

  private
   def user_params
      params.require(:user).permit(:name, :email, :employee_number, :division, :gender,
       :started_at, :birthday, :employee, :password, :password_confirmation, :uploaded_thumbnail)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<%= form_for(:post, url: search_user_path(@user), method: :get, remote: true) do |f| %>
   <%= f.text_field :word, class: "search-form", placeholder: "フリーワード検索しよう！" %>
   <% unless @published == true %>
      <%= f.hidden_field :published, value: "0" %>
   <% end %>
   <%= button_tag sanitize('<i class="fa fa-search"></i>'), type: "submit",
      class: "search-btn" %>
<% end %>

app/views/users/edit.html.erb
<div id="container-left">
   <%= render('shared/user_status') %>
</div>

<div id="container-right">
   <div id="user-form" class="content-box">
      <div class="content-header">
         <p>アカウントの編集</p>
      </div>
      <%= form_for(@user) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>

         <ul class="form-line">
            <li class="form-label">氏名</li>
            <li class="form-value"><%= @user.name %></li>
         </ul>

         <div class="form-line">
            <p class="form-label">Eメール</p>
            <%= f.text_field :email, placeholder: 'Eメール(必須)', class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">社員番号</p>
            <p class="form-value"><%= @user.employee_number %></p>
         </div>

         <div class="form-line">
            <p class="form-label">所属部署</p>
            <p class="form-value"><%= @user.division %></p>
         </div>

         <div class="form-line">
            <p class="form-label">性別</p>
            <p class="form-value"><%= @user.gender %></p>
         </div>

         <div class="form-line">
            <p class="form-label">プロフィール画像</p>
            <%= f.file_field :uploaded_thumbnail, class: 'form-file form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">入社年月</p>
            <p class="form-value"><%= @user.started_at.strftime("%Y年%m月%d日") %></p>
         </div>

         <div class="form-line">
            <p class="form-label">誕生日</p>
            <p class="form-value"><%= @user.birthday.strftime("%Y年%m月%d日") %></p>
         </div>

         <div class="form-line">
            <p class="form-label">パスワード</p>
            <%= link_to "パスワード変更へ", edit_password_path(@user), class: "form-link form-value" %>
         </div>

         <%= f.submit '登録', class: 'btn form-submit' %>
      <% end %>
   </div>

</div>

app/views/users/edit_password.html.erb
<div id="container-left">
   <div id="user-profile" class="content-box">
      <img src="https://www.causes.com/assets/avatar_placeholder-9a2f53db6270aa02b5ae2c5af1ffc72b.svg" id="user-thumbnail">
      <div id="user-information">
         <p id="user-name">吉岡　隆弘  さん</p>
         <p id="user-division">滋賀工場技術課</p>
         <a href="#">編集する</a>
         <ul id="user-archivements">
            <li class="user-archivement">
               <p class="section">投稿</p>
               <p class="count">12</p>
            </li>
            <li class="user-archivement">
               <p class="section">診断</p>
               <p class="count">6</p>
            </li>
            <li class="user-archivement">
               <p class="section">学習</p>
               <p class="count">4</p>
            </li>
         </ul>
      </div>
   </div>
</div>

<div id="container-right">
   <div id="user-form" class="content-box">
      <div class="content-header">
         <p>パスワードの設定</p>
      </div>
      <%= form_for(:password, url: update_password_path(@user)) do |f| %>

         <div class="form-line">
            <p class="form-label">現在のパスワード</p>
            <%= f.password_field :current_password, class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">新しいパスワード</p>
            <%= f.password_field :new_password, class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">パスワードの確認</p>
            <%= f.password_field :password_confirmation, class: 'form-input form-user' %>
         </div>

         <%= f.submit '登録(メール送信)', class: 'btn form-submit' %>
      <% end %>
   </div>

</div>

app/views/users/index.html.erb
<div class="content-box">
   <h1>User Index</h1>
</div>

   <ul>
      <% @users.each do |user| %>
      <li class="content-box">
         <p>Name: <%= user.name %></p>
         <p>Email: <%= user.email %></p>
         <p>Employee number: <%= user.employee_number %></p>
         <p>Division: <%= user.division %></p>
         <p>Gender: <%= user.gender %></p>
         <p>Started_at: <%= user.started_at %></p>
         <p>Birthday: <%= user.birthday %></p>
         <p>Employee: <%= user.employee %></p>
      </li>
      <% end %>
   </ul>

app/views/users/new.html.erb
<div id="container-left">
   <%= render('shared/user_status') %>
</div>

<div id="container-right">
   <div id="user-form" class="content-box">
      <div class="content-header">
         <p>アカウントの作成</p>
      </div>
      <%= form_for(@user) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>

         <div class="form-line">
            <p class="form-label">氏名</p>
            <%= f.text_field :name, placeholder: '氏名(必須)', class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">Eメール</p>
            <%= f.text_field :email, placeholder: 'Eメール(必須)', class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">社員番号</p>
            <%= f.text_field :employee_number, placeholder: '社員番号(必須)', class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">所属部署</p>
            <%= f.text_field :division, placeholder: '所属部署(必須)', class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">性別</p>
            <%= f.select :gender, ['男', '女'], { include_blank: '性別(必須)' },
             class: 'form-select form-user' %></p>
         </div>

         <div class="form-line">
            <p class="form-label">入社年月</p>
            <%= f.date_field :started_at, class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">誕生日</p>
            <%= f.date_field :birthday, class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">ユーザーの所属</p>
            <%= f.select :employee, {'新人' => true, '人事' => false}, { include_blank: '雇用者？(必須)' },
            class: 'form-select form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">パスワード</p>
            <%= f.password_field :password, class: 'form-input form-user' %>
         </div>

         <div class="form-line">
            <p class="form-label">パスワードの確認</p>
            <%= f.password_field :password_confirmation, class: 'form-input form-user' %>
         </div>

         <%= f.submit '登録(メール送信)', class: 'btn form-submit' %>
      <% end %>
   </div>

</div>

app/views/users/search_user.js.erb
$('#posts').html("<%= escape_javascript(render('posts/posts'))%>");

app/views/users/show.html.erb
<div id="container-left">
   <%= render('shared/user_status') %>
</div>

<div id="container-right">
   <div id="condition-summary" class="content-box">
      こころチェックの状況を定義
   </div>
   <div id="post-option">
      <% if @user == current_user %>
         <div id="search-own-user" class="search content-box">
            <%= render 'users/search' %>
         </div>
         <div id="toggle-draft" class="content-box">
            <a href="#" id="toggled-publish" class="toggle-button toggle-active"><i class="fa fa-book"></i><span>公開中</span></a>
            <%= link_to user_path(@user, published: "0"), id: 'toggled-draft', class: "toggle-button", remote: true do %><i class="fa fa-pencil-square-o"></i><span>下書き</span><% end %>
         </div>
      <% else %>
         <div id="search-another-user" class="search content-box">
            <%= render 'users/search' %>
         </div>
      <% end %>
   </div>
   <div id="posts">
      <%= render 'posts/posts' %>
   </div>
</div>

app/views/users/show.js.erb
<% if @published == true %>
   $('.search form').html('<%= escape_javascript(render("users/search")) %>');
   $('#toggle-draft').html('<a href="#" id="toggled-publish" class="toggle-button toggle-active"><i class="fa fa-book"></i><span>公開中</span></a>' +
                           '<%= link_to user_path(@user, published: "0"), id: "toggled-draft", class: "toggle-button", remote: true do %>' +
                           '<i class="fa fa-pencil-square-o"></i><span>下書き</span><% end %>');
<% else %>
   $('.search form').html('<%= escape_javascript(render("users/search")) %>');
   $('#toggle-draft').html('<%= link_to user_path(@user), id: "toggled-publish", class: "toggle-button", remote: true do %>' +
                           '<i class="fa fa-book"></i><span>公開中</span><% end %>' +
                           '<a href="#" id="toggled-draft" class="toggle-button toggle-active"><i class="fa fa-pencil-square-o"></i><span>下書き</span></a>');
<% end %>
$('#posts').html('<%= escape_javascript(render("posts/posts")) %>');