config/routes.rb
Rails.application.routes.draw do

   root  'static_pages#home'

   # Routes for static pages
   get '/home', to: 'static_pages#home'
   get '/search_home', to: 'static_pages#search_home'
   get '/help', to: 'static_pages#help'
   get '/about', to: 'static_pages#about'
   get '/convention', to: 'static_pages#convention'

   # Routes for users
   # TODO Need to rename http parameters when the time to create HR page comes
   resources 'users'
   get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
   patch 'users/:id/edit_password', to: 'users#update_password', as: 'update_password'
   get 'search_user/:id', to: 'users#search_user', as: 'search_user'

   # Routes for sessions
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout/:id', to: 'sessions#destroy', as: 'logout'

   # Routes for account managements
   get '/account_activation/:id', to: 'account_managements#account_activation', as: 'account_activation'
   get '/password_reset', to: 'account_managements#password_reset_new'
   post '/password_reset', to: 'account_managements#password_reset_create'

   # Routes for file uploaders
   resources 'uploaders', only: [] do
     member do
      get :user_thumbnail, as: :user_thumbnail
     end
   end

   # Routes for posts
   resources 'posts', only: [:new, :show, :edit, :create, :update, :destroy]

   # Routes for comments
   resources 'comments', only: [:edit, :create, :update, :destroy]
   get '/comments/:id', to: 'comments#new', as: 'new_comment'

   # Routes for reactions
   resources 'reactions', only: [:destroy]
   get '/reactions/:id', to: 'reactions#create', as: "new_reaction"

   resources 'conditions', only: [:show, :edit, :update]
   get '/conditions/:id/index', to: 'conditions#index', as: 'conditions'
   post '/conditions/new', to: 'conditions#create', as: "new_condition"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
   belongs_to :user
   has_many :comments, dependent: :destroy
   has_many :reactions, dependent: :destroy
   has_many :conditions, dependent: :destroy

   paginates_per 10

   validates :user_id, presence: true
   validates :content, presence: true,
                       length: { maximum: 1000 }
   validates :condition, format: { with: /blank|success|info|warning|danger/ }
   validate :not_daily?
   validates :post_type, format: { with: /daily|condition|learning/ }
   validates :published, inclusion: { in: [true, false] }

   private
      def not_daily?
         if self.post_type == "condition" || self.post_type == "learning"
             errors.add(:condition, 'is not about the daily') if self.condition != "blank"
         end
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :is_logged_in?
   before_action :url_log

  def new
     @user = current_user
     @post = Post.new
     respond_to do |format|
        format.js {}
     end
  end

  def show
     @user = current_user
     @post = Post.find(params[:id])
     respond_to do |format|
      format.js {}
     end
  end

  def edit
     @user = current_user
     @post = Post.find(params[:id])
     respond_to do |format|
       format.js {}
     end
  end

  def create
     @user = current_user
     @post = current_user.posts.build(post_params)
     respond_to do |format|
        if @post.save
           flash[:success] = "新しい記録を投稿しました。"
           format.html { redirect_back_to(root_url) }
           format.js { render 'posts/create' }
        else
           format.html { redirect_back_to(root_url) }
           format.js { render 'posts/create' }
        end
     end

  end

  def update
     @user = current_user
     @post = Post.find(params[:id])
      respond_to do |format|
         if @post.update_attributes(post_params)
            flash[:success] = "記録を再投稿しました。"
            format.html { redirect_back_to(root_url) }
            format.js { render 'posts/update' }
         else
            format.html { redirect_back_to(root_url) }
            format.js { render 'posts/update' }
         end
      end
  end

  def destroy
     @user = current_user
     @post = Post.find(params[:id])
     if @post.destroy
        flash[:info] = "記録を削除しました。"
        redirect_back_to(root_url)
     else
        flash[:danger] = "この投稿は削除できません"
        redirect_back_to(root_url)
     end
  end

  private
   def post_params
      params.require(:post).permit(:content, :condition, :post_type, :published)
   end
end

app/helpers/posts_helper.rb
module PostsHelper

   def post_class(post)
      case post.post_type
      when "daily"
         case post.condition
         when "success"
            return "success"
         when "info"
            return "info"
         when "warning"
            return "warning"
         when "danger"
            return "danger"
         else
            return "blank"
         end
      when "condition"
         return "condition"
      when "learning"
         return "learning"
      else
      end
   end

   def post_category(post)
      case post.post_type
      when "daily"
         return "投稿"
      when "condition"
         return "診断"
      when "learning"
         return "学習"
      else
      end
   end

   def post_icon(post)
      case post.post_type
      when "daily"
         case post.condition
         when "success"
            return "success.png"
         when "info"
            return "info.png"
         when "warning"
            return "warning.png"
         when "danger"
            return "danger.png"
         else
            return ""
         end
      when "condition"
         return "condition.png"
      when "learning"
         return "learning.png"
      else
      end
   end

   def post_condition(post)
      case post.condition
      when "success"
         return "余力あり"
      when "info"
         return "ちょうど"
      when "warning"
         return "溜め気味"
      when "danger"
         return "手一杯"
      else
         return ""
      end
   end

   def post_content(post)
      return post.content.slice(0, 140)
   end

   def post_template(type)
      case type
      when "condition"
         return {
               content: "「心の状態」は周囲には見えにくく、一方で変わりやすいもの。
                        タイミングよく適切なフォローが重要です。",
               condition: "blank",
               post_type: "condition",
               published: false
                }
      when "learning"
         return ""
      else
      end
   end

end

app/views/posts/_form.html.erb
   <div id="blackout" class="ajax-content"></div>
   <div id="post-form" class="content-box ajax-content">
      <div class="content-header">
         <p>新しい投稿</p>
      </div>
      <%= form_for(@post, remote: true) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>

         <div class="form-line">
            <p class="content-section"><%= "#{Date.today.strftime("%Y年%m月%d日")}のあなたの記録"%></p>
            <%= f.text_area :content, placeholder: "#{Date.today.strftime("%Y年%m月%d日")}を振り返って記録しよう", class: 'form-input form-post' %>
         </div>

         <div class="form-line">
            <p class="content-section">今の仕事状況</p>
            <ul class="form-condition">
               <li><%= f.radio_button :condition, 'success', class: "condition-button button-success" %><p class="condition-label">余力あり</p></li>
               <li><%= f.radio_button :condition, 'info', class: "condition-button button-info" %><p class="condition-label">ちょうど</p></li>
               <li><%= f.radio_button :condition, 'warning', class: "condition-button button-warning" %><p class="condition-label">溜め気味</p></li>
               <li><%= f.radio_button :condition, 'danger', class: "condition-button button-danger" %><p class="condition-label">手一杯</p></li>
            </ul>
         </div>

         <%= f.hidden_field :post_type, value: "daily" %>

         <% unless @post.published? %>
            <div class="form-line">
               <p class="content-section">投稿形態</p>
               <%= f.select :published, {'投稿する': true, '下書きとして保存': false}, {}, class: 'form-select form-post' %>
            </div>
         <% end %>

         <%= f.submit '投稿する', class: 'btn form-submit'%>
      <% end %>
   </div>

app/views/posts/_posts.html.erb
   <% @posts.each do |post| %>
      <% if post.post_type != "condition" || condition_summary("class", post) != "nothing" %>
         <div id="post-<%= post.id %>" class="post content-box">
            <div class="post-main">
               <div class="post-imgs">
                  <%= image_tag(show_user_thumbnail(post.user), class: 'post-thumbnail') %>
                  <div class="post-condition">
                     <p class="post-condition-about post-about-<%= post_class(post) %>"><%= post_category(post)%></p>
                     <%= image_tag(post_icon(post), class: 'post-icon') %>
                     <% if post.post_type == "daily" %>
                     <p class="post-condition-result post-result-<%= post_class(post) %>"><%= post_condition(post)%></p>
                     <% end %>
                  </div>
               </div>
               <div class="post-contents">
                  <ul class="post-header">
                     <li class="post-user"><%= post.user.name %>の投稿</li>
                     <li class="post-posted-at"><%= post.updated_at.strftime("%Y/%m/%d %H:%M") %> 更新</li>
                     <% if post.user == current_user %>
                        <li class="post-command">
                           <%= link_to edit_post_path(post), remote: true do %><i class="fa fa-pencil"></i><% end %>
                           <%= link_to post_path(post), method: :delete do %><i class="fa fa-trash-o"></i><% end %>
                        </li>
                     <% end %>
                  </ul>
                  <p class="post-line">
                     <%= post_content(post) %>
                     <% if post.content.length >= 140 %>
                        <%= link_to post_path(post), remote: true do %><i class="fa fa-angle-double-right"></i>続きを読む<% end %>
                     <% end %>
                  </p>
               </div>
            </div>
            <% if post.published? %>
            <div class="post-reaction">
               <% if post.reactions.find_by(user_id: current_user.id).nil? %>
                  <%= link_to reaction_path(post), class: 'reaction-default', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= post.reactions.count %></span><% end %>
               <% else %>
                  <%= link_to reaction_path(post), method: :delete, class: 'reaction-reacted', remote: true do %><i class="fa fa-thumbs-o-up"></i><span class="reaction-str">いいね</span><span><%= post.reactions.count %></span><% end %>
               <% end %>
               <% if post.reactions.count >= 1 %>
               <ul class="post-reaction-list">
                  <% post.reactions.each do |reaction| %>
                  <li><%= reaction.user.name %></li>
                  <% end %>
               </ul>
               <% end %>
               <%= link_to new_comment_path(post), remote: true do %><i class="fa fa-comment-o"></i><span class="reaction-str">コメント</span><span><%= post.comments.count %></span><% end %>
            </div>
            <% end %>
         </div>
      <% end %>
   <% end %>

   <div id="pagination">
      <%= paginate @posts %>
   </div>

app/views/posts/edit.html.erb
<div id="container-left">
   <%= render('shared/user_status') %>
</div>

<div id="container-right">
   <div id="post-form" class="content-box">
      <div class="content-header">
         <p>新しい投稿</p>
      </div>
      <%= form_for(@post) do |f| %>
         <%= render 'shared/error_messages', object: f.object %>

         <div class="form-line">
            <p class="content-section"><%= "#{Date.today}時のあなたの記録"%></p>
            <%= f.text_area :content, placeholder: "#{Date.today}を振り返って記録しよう", class: 'form-input form-post' %>
         </div>

         <div class="form-line">
            <p class="content-section">今の仕事状況</p>
            <ul class="form-condition">
               <li><%= f.radio_button :condition, 'blank', class: "condition-button button-blank" %><p class="condition-label">未入力</p></li>
               <li><%= f.radio_button :condition, 'comfort', class: "condition-button button-comfort" %><p class="condition-label">余力あり</p></li>
               <li><%= f.radio_button :condition, 'safe', class: "condition-button button-safe" %><p class="condition-label">ちょうど</p></li>
               <li><%= f.radio_button :condition, 'caution', class: "condition-button button-caution" %><p class="condition-label">溜め気味</p></li>
               <li><%= f.radio_button :condition, 'danger', class: "condition-button button-danger" %><p class="condition-label">手一杯</p></li>
            </ul>
         </div>

         <%= f.hidden_field :post_type, value: "daily" %>

         <%= f.submit '投稿する', class: 'btn form-submit'%>
      <% end %>
   </div>
</div>

app/views/posts/edit.js.erb
$('body').prepend("<%= escape_javascript(render('posts/form')) %>");
$('#blackout').on('click', function(){
   $('.ajax-content').remove();
});

$(".condition-button").on('click', function(){
   $(".condition-button").next().removeClass("label-activated");
   $(this).next().addClass("label-activated");
});

app/views/posts/new.js.erb
$('body').prepend("<%= escape_javascript(render('posts/form')) %>");
$('#blackout').on('click', function(){
   $('.ajax-content').remove();
});

$(".condition-button").on('click', function(){
   $(".condition-button").next().removeClass("label-activated");
   $(this).next().addClass("label-activated");
});

app/views/posts/show.js.erb
$('#post-<%= @post.id%> .post-line').html('<%= @post.content %>');