config/routes.rb
Rails.application.routes.draw do

   root  'static_pages#home'

   # Routes for static pages
   get '/home', to: 'static_pages#home'
   get '/search_home', to: 'static_pages#search_home'
   get '/help', to: 'static_pages#help'
   get '/about', to: 'static_pages#about'
   get '/convention', to: 'static_pages#convention'

   # Routes for users
   # TODO Need to rename http parameters when the time to create HR page comes
   resources 'users'
   get 'users/:id/edit_password', to: 'users#edit_password', as: 'edit_password'
   patch 'users/:id/edit_password', to: 'users#update_password', as: 'update_password'
   get 'search_user/:id', to: 'users#search_user', as: 'search_user'

   # Routes for sessions
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout/:id', to: 'sessions#destroy', as: 'logout'

   # Routes for account managements
   get '/account_activation/:id', to: 'account_managements#account_activation', as: 'account_activation'
   get '/password_reset', to: 'account_managements#password_reset_new'
   post '/password_reset', to: 'account_managements#password_reset_create'

   # Routes for file uploaders
   resources 'uploaders', only: [] do
     member do
      get :user_thumbnail, as: :user_thumbnail
     end
   end

   # Routes for posts
   resources 'posts', only: [:new, :show, :edit, :create, :update, :destroy]

   # Routes for comments
   resources 'comments', only: [:edit, :create, :update, :destroy]
   get '/comments/:id', to: 'comments#new', as: 'new_comment'

   # Routes for reactions
   resources 'reactions', only: [:destroy]
   get '/reactions/:id', to: 'reactions#create', as: "new_reaction"

   resources 'conditions', only: [:show, :edit, :update]
   get '/conditions/:id/index', to: 'conditions#index', as: 'conditions'
   post '/conditions/new', to: 'conditions#create', as: "new_condition"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div id="footer">
   <p id="footer-title"><span>A</span>ctive<span>R</span>eco<span>B</span>ook</p>
   <ul id="footer-main">
      <li class="footer-content"><%= link_to "Active Reco Book とは", about_path %></a></li>
      <li class="footer-content"><%= link_to "よくある質問", help_path %></li>
      <li class="footer-content"><%= link_to "利用規約", convention_path %></li>
   </ul>
   <p id="footer-copyright">© 2017 Shantty_Y</p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
   <ul id="header-main">

      <% if is_logged? %>
         <li id="header-menu" class="header-content header-icon"><i class="fa fa-bars"></i></li>
      <% else %>
         <li id="header-dammy" class="header-content"></li>
      <% end %>

      <li id="header-title" class="header-content">
         <%= link_to home_path do %>
            <span>A</span>ctive<span>R</span>eco<span>B</span>ook
         <% end %>
      </li>

      <% if is_logged?%>
         <li id="header-user" class="header-content header-icon"><i class="fa fa-home"></i></li>
         <li id="header-notify" class="header-content header-icon">
            <p id="notify-count">1</p>
            <i class="fa fa-clipboard"></i>
         </li>
      <% end %>

   </ul>
   <% if is_logged? %>
      <ul id="header-menu-contents">
         <li class="header-menu-content"><%= link_to "新しい投稿", new_post_path, remote: true %></li>
         <li class="header-menu-content"><%= link_to "こころチェック", condition_path(current_user) %></li>
         <li class="header-menu-content"><a href="">webラーニング</a></li>
      </ul>
   <% end %>
</div>

<% if is_logged? %>
   <div id="dropdown-menu" class="dropdown-content">
      <ul class="menu-items">
         <li class="menu-item"><%= link_to new_post_path, remote: true do %><i class="fa fa-plus"></i>新しい投稿<% end %></li>
         <li class="menu-item"><%= link_to condition_path(current_user) do %><i class="fa fa-heartbeat"></i>こころチェック<% end %></li>
         <li class="menu-item"><a href=""><i class="fa fa-laptop"></i>Webラーニング</a></li>
      </ul>
   </div>
   <div id="dropdown-notify" class="dropdown-content">
      <ul class="menu-items">
         <li class="menu-item">
            <a class="notify-box" href="#">
               <img src="https://www.causes.com/assets/avatar_placeholder-9a2f53db6270aa02b5ae2c5af1ffc72b.svg" class="notify-thumbnail">
               <div class="notify-content">
                  <p class="notify-line">酒寄 辰巳さんがあなたの投稿にコメントしました。</p>
                  <p class="notify-created-at">20時間前</p>
               </div>
            </a>
         </li>
         <li class="menu-item">
            <a class="notify-box" href="#">
               <img src="https://www.causes.com/assets/avatar_placeholder-9a2f53db6270aa02b5ae2c5af1ffc72b.svg" class="notify-thumbnail">
               <div class="notify-content">
                  <p class="notify-line">酒寄 辰巳さんがあなたの投稿にコメントしました。</p>
                  <p class="notify-created-at">20時間前</p>
               </div>
            </a>
         </li>
         <li class="menu-item">
            <a class="notify-box" href="#">
               <img src="https://www.causes.com/assets/avatar_placeholder-9a2f53db6270aa02b5ae2c5af1ffc72b.svg" class="notify-thumbnail">
               <div class="notify-content">
                  <p class="notify-line">酒寄 辰巳さんがあなたの投稿にコメントしました。</p>
                  <p class="notify-created-at">20時間前</p>
               </div>
            </a>
         </li>
         <li class=" menu-item">
            <a class="notify-box" href="#">
               <img src="https://www.causes.com/assets/avatar_placeholder-9a2f53db6270aa02b5ae2c5af1ffc72b.svg" class="notify-thumbnail">
               <div class="notify-content">
                  <p class="notify-line">酒寄 辰巳さんがあなたの投稿にコメントしました。</p>
                  <p class="notify-created-at">20時間前</p>
               </div>
            </a>
         </li>
      </ul>
   </div>

   <div id="dropdown-user" class="dropdown-content">
      <ul class="menu-items">
         <li class="menu-item"><%= link_to user_path(current_user) do %><i class="fa fa-user"></i>ユーザーページ<% end %></li>
         <li class="menu-item"><%= link_to edit_user_path(current_user) do %><i class="fa fa-cog"></i>設定<% end %></li>
         <li class="menu-item"><%= link_to logout_path(current_user), method: :delete do %><i class="fa fa-sign-out"></i>ログアウト<% end %></li>
      </ul>
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveRecoBook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='//fonts.googleapis.com/css?family=Fascinate' rel='stylesheet'>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
   <!--         Header         -->
   <%= render 'layouts/header' %>

   <!--        Contents        -->
   <div id="container">
      <%= render 'shared/flash' %>
      <%= yield %>
   </div>

   <!--         Footer         -->
   <%= render 'layouts/footer' %>
  </body>
</html>